### ISSUE TITLE
 why compilation result got error ....undefined reference to `lv_scr_load_anim' ....

### ISSUE THREAD

**Issue by baeosk103** [nu1504ta0609sa0902/CYD_practice_projects#1]
Hi 

I download the CYD_practice_projects folder from Github  and start  learning with your good you tube tutorial. I move the EEZ_arc_events folder which they are all completed with your several ui files from eez  and the EEZ_arc_events.ino. 

My environment is 
- arduino Ide is version 2.3.3 
- my lvgl is version 9.0 and 
- the TFT-ESPI is version 2.5.43  
- My practice lesson : EEZ_arc_events folder

my notebook work on the compiling for  a few minutes , I get the error compiling message as  following.

c:/users/admin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\objs.a(ui.c.o):(.literal.loadScreen+0x4): undefined reference to `lv_scr_load_anim'
c:/users/admin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\objs.a(ui.c.o): in function `loadScreen':

C:\Users\Admin\Documents\Arduino\EEZ_arc_events/ui.c:51: undefined reference to `lv_scr_load_anim'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

I am new for the EEZ -LVGL so I need  some advise for the reason why the system compiIation show  error message  and how can  I  fix this errors. 

I  try on the another practice example in the folder ,they also show  me the same error message...undefined reference to `lv_scr_load_anim' ...

My questions are
1. Are the error  from my environment /versions of  the system 
2. Are the error from the specific setup of any ui-file from the EZZ
3. Are the error from the lv_conf.h file of the lvgl
4. Are the error from the lv_scr_load_anim configuration parameter

Your help and advise will be very appreciated.

Thanks
"My dream will happen"

**Comment by nu1504ta0609sa0902** [comment]
I'm a beginner my self so don't know what that error means.

All I can say is update to lvgl 9.1 and than copy lv_conf_template file and rename it to lv_conf.

See here for more details on how to configure it:
https://randomnerdtutorials.com/lvgl-cheap-yellow-display-esp32-2432s028r/

If you can get the example working there all the rest will work.

**Comment by nu1504ta0609sa0902** [comment]
Hope the above works.

**Comment by baeosk103** [comment]
Great , I will try  and  update the status...

Thanks

**Comment by baeosk103** [comment]
Hi,

I test with LVGL9.1 , they are  perfect .

.... I can fly....My dream come true....

Cheers
![IMG_20241002_161534](https://github.com/user-attachments/assets/179dc4c2-0172-43a0-89cd-0dc8dbe07aca)
